### PR TITLE
"Can't find variable: self" in react native

### PR DESCRIPTION
**Pull request by Chachaproper**
Issue: https://github.com/GoogleChrome/proxy-polyfill/issues/26

### CODE REVIEW

**Comment by Chachaproper** [comment]
@googlebot I signed it!

**Comment by ramosdevgrid** [comment]
Hello!
Can you inform why this PR was closed? This problem was solved in the React side?
Thanks!

**Comment by samthor** [comment]
I'm also confused.

I also don't really know why the check has to be this way. Surely we can `typeof process` and `typeof global` etc. But I'm not an expert on what exists in global scope of different runtimes.

**Comment by Chachaproper** [comment]
Hello.
I think that this solution does not solve the problem аnd does not look nice.

**Comment by nickleach** [comment]
@Chachaproper any other thoughts other than it doesn't look nice? This fix is needed

**Pull request closed without merging**
