### PR TITLE
fix strict mode 'let' error

### PR DESCRIPTION
**Pull request by herman1vdb**
Fix Unexpected reserved word 'let' in strict mode

### CODE REVIEW

**Comment by samthor** [comment]
What's the goal here—to run this code in ES5 mode? We include the minified, compiled version inside `proxy.min.js`.

**Comment by edzis** [comment]
This is an issue for me too when running the build on my `create-react-app` project with TypeScript that uses `proxy-polyfill` as a dependency of https://github.com/engineforce/ImmutableAssign.

I believe my problem would be resolved if `package.json` stated the minified file as the `main` entry.

See log below for context and link to recommendations from `create-react-app`:

```
$ react-scripts-ts build
Creating an optimized production build...
ts-loader: Using typescript@2.5.3 and /Users/###/###/tsconfig.json
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/proxy-polyfill/proxy.js:24

Read more here: http://bit.ly/2tRViJ9
```

**Comment by tracykm** [comment]
This is also an issue for us. We are using webpack and uglify can't handle newer javascript features.

```
ERROR in 1.46c93dbcf6b01bcdac47.chunk.js from UglifyJs
Unexpected token: name (lastRevokeFn) [./node_modules/proxy-polyfill/proxy.js:24,0][1.46c93dbcf6b01bcdac47.chunk.js:3610,6]
```

**Comment by herman1vdb** [comment]
@samthor Yes you're right. Maybe the issue is more the project structure that's the problem, we could have 2 outputs (proxy.min.js and proxy.js) and this file (currently [proxy.js](https://github.com/GoogleChrome/proxy-polyfill/blob/master/proxy.js)) as the source. Does that make sense?

**Comment by samthor** [comment]
We've just released v0.2.0, which splits out the code a bit into:

* ES6 source that doesn't export, plus an index file which exports to global scope
* we've left the minified main file

**Pull request closed without merging**
