### PR TITLE
Included support for property definitions.

### PR DESCRIPTION
**Pull request by richardspence**
Property definitions weren't being proxied correctly.  This walks the prototype chain up the super classes and ensures those properties will be passed to the get handler correctly

### CODE REVIEW

**Comment by richardspence** [comment]
Fixes #81

**Comment by richardspence** [comment]
@samthor is this something you can review?

**Comment by samthor** [comment]
No, I don't work at Google any more.

I'll throw @bramus under the bus?

**Comment by richardspence** [comment]
@bramus would you be able to review this?

**Pull request merged**
